{application,zipper,
             [{description,"Generic Zipper Implementation for Erlang"},
              {vsn,"1.1.0"},
              {applications,[kernel,stdlib]},
              {modules,[zipper,zipper_default]},
              {registered,[]},
              {maintainers,["Inaka"]},
              {licenses,["Apache 2.0"]},
              {links,[{"GitHub","https://github.com/inaka/zipper"}]},
              {build_tools,["rebar3"]}]}.
