name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: Taure/erlang-ci/.github/workflows/ci.yml@5f7a6d94246e8a0b12065cffb25a218138fca431
    permissions:
      contents: write
      pull-requests: write
    with:
      enable-audit: true
      enable-summary: true
    secrets: inherit
