name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: Taure/erlang-ci/.github/workflows/ci.yml@df6f46cfd6812dab0d9f825a2fdf69f85e2f92b2
    permissions:
      contents: write
      pull-requests: write
    with:
      enable-audit: true
      enable-summary: true
    secrets: inherit
