name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: Taure/erlang-ci/.github/workflows/ci.yml@dc560fbe8e4e39898dd808645fc1d3e69d248429
    permissions:
      contents: write
      pull-requests: write
    with:
      enable-audit: true
      enable-summary: true
    secrets: inherit
